Repository openshift-pipelines/operator, pull requests merged in 2025-05, with the labels that each got.

#4211 Update project.yaml
  project.yaml
Labels: approved

#4222 Update project.yaml
  project.yaml
Labels: approved

#4224 Update Makefile
  Makefile
Labels: approved

#4228 Update project yaml
  project.yaml
Labels: approved

#4239 Update docker-build-ta.yaml
  .tekton/docker-build-ta.yaml
Labels: approved

#4249 Update project.yaml
  project.yaml
Labels: approved

#4287 [1-18-1] Rebuild Index images
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4298 [bot:openshift-pipelines-operator:main] update konflux configuration
  .tekton/operator-main-bundle-pull-request.yaml
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-pull-request.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-pull-request.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-pull-request.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: approved, automated, hack

#4349 [bot:openshift-pipelines-operator:main] update konflux configuration
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: automated, hack

#4407 Fix CVE for x/crypto
  upstream/go.mod
  upstream/go.sum
  upstream/vendor/golang.org/x/crypto/ssh/handshake.go
  upstream/vendor/golang.org/x/crypto/ssh/server.go
  upstream/vendor/golang.org/x/sys/cpu/cpu.go
  upstream/vendor/golang.org/x/sys/cpu/cpu_x86.go
  upstream/vendor/golang.org/x/sys/unix/auxv.go
  upstream/vendor/golang.org/x/sys/unix/auxv_unsupported.go
  upstream/vendor/golang.org/x/sys/unix/syscall_solaris.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  upstream/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  upstream/vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  upstream/vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  upstream/vendor/golang.org/x/sys/unix/ztypes_linux.go
  upstream/vendor/modules.txt
Labels: approved

#4499 rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4508 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/update-sources-next.yaml
Labels: automated, hack

#4511 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/update-sources-next.yaml
Labels: automated, hack

#4513 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/update-sources-next.yaml
Labels: automated, hack

#4514 [bot:openshift-pipelines-operator:next] update konflux configuration
  .tekton/operator-next-bundle-pull-request.yaml
  .tekton/operator-next-bundle-push.yaml
  .tekton/operator-next-operator-pull-request.yaml
  .tekton/operator-next-operator-push.yaml
  .tekton/operator-next-proxy-pull-request.yaml
  .tekton/operator-next-proxy-push.yaml
  .tekton/operator-next-webhook-pull-request.yaml
  .tekton/operator-next-webhook-push.yaml
Labels: automated, hack

#4547 1-18-1 rebuild index images
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4591 1-15-3 rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4647 Create .placeholder
  .konflux/patches/.placeholder
Labels: approved

#4709 Update bundle info for 1.16
  .konflux/olm-catalog/index/v4.12/catalog-template.json
  .konflux/olm-catalog/index/v4.14/catalog-template.json
Labels: approved

#4716 Update skiprange info for 1.16
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
Labels: approved

#4723 Rebuild indes images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4738 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/update-sources-next.yaml
Labels: automated, hack

#4753 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/update-sources-next.yaml
Labels: automated, hack

#4752 [bot] Update next from tektoncd/operator to 41fd64f439c5cea5a4c34661f…
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  .konflux/patches/0000-go1.23.patch
Labels: approved, lgtm

#4754 [bot:openshift-pipelines-index-4.18:next] update konflux configuration
  .tekton/operator-next-index-4.18-pull-request.yaml
  .tekton/operator-next-index-4.18-push.yaml
Labels: automated, hack

#4775 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/auto-merge-upstream-main.yaml
  .github/workflows/update-sources-main.yaml
  .tekton/operator-main-bundle-pull-request.yaml
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-pull-request.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-pull-request.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-pull-request.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: automated, hack

#4816 1-18-1 update catalog to add 1.15.3 image
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
Labels: approved

#4836 1-18-1 rebuild index images for prod
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4862 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/auto-merge-upstream-release-v1.19.x.yaml
  .github/workflows/update-sources-release-v1.19.x.yaml
Labels: automated, hack

#4868 [bot:openshift-pipelines-operator:main] update konflux configuration
  .github/workflows/auto-merge-upstream-release-v1.19.x.yaml
  .github/workflows/update-sources-release-v1.19.x.yaml
Labels: automated, hack
