Repository openshift-pipelines/operator, pull requests merged in 2025-03, with the labels that each got.

#2474 Add fbc-fips-check task to fbc-build pipeline
  .tekton/fbc-build.yaml
Labels: approved

#2475 [1.18]Add fbc-fips-check task to fbc-build pipeline
  .tekton/fbc-build.yaml
Labels: approved

#2476 [1.18]Add ImageDigestMirrorSet to solve Could not find Image mirror set
  .tekton/images-mirror-set.yaml
Labels: approved

#2477 testing index images
  .tekton/fbc-build.yaml
Labels: approved

#2540 Update base image for 4.18 and image value for IMAGE_ADDONS_TKN_CLI_SERVE
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
  project.yaml
Labels: approved

#2544 revert the IMAGE_ADDONS_TKN_CLI_SERVE as release has not executed
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  project.yaml
Labels: approved

#2549 update tag for 4.15 and 4.16 dockerfile
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
Labels: approved

#2554 update render template to make it work with 4.17 and later version
  .github/workflows/index-render-template-1-18.yaml
Labels: approved

#2559 Fix if condition issue to render the template for 4.17
  .github/workflows/index-render-template-1-18.yaml
Labels: approved

#2565 Add entries for olm.channel with supported versions
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
Labels: approved

#2570 Add channels and bundles for all the supported versions
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
Labels: approved

#2571 Revert "[bot:1.18] Update v4.16 generate catalog"
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog/openshift-pipelines-operator-rh/catalog.json
Labels: approved

#2573 Update jq query to replace SHA of the olm.bundle without effecting other sha of a olm.bundle
  .github/workflows/index-render-template-1-18.yaml
Labels: approved

#2588 update catalog-template.json as per the channels available in ocp base images
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
Labels: approved

#2610 Update jq query to update bundle image from project yaml to catalog-template.json
  .github/workflows/index-render-template-1-18.yaml
Labels: approved

#2611 Add 1.18.0 version to latest channel
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
Labels: approved

#2604 update image for IMAGE_ADDONS_TKN_CLI_SERVE
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  .konflux/olm-catalog/index/v4.15/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.16/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.17/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.18/catalog/openshift-pipelines-operator-rh/catalog.json
  project.yaml
Labels: approved

#2617 Update operator-1-18-index-4-18-push.yaml
  .tekton/operator-1-18-index-4-18-push.yaml
Labels: approved

#2685 Delete .tekton/docker-build-ta.yaml as we are maintaining in main branch
  .tekton/docker-build-ta.yaml
Labels: approved

#2733 Rebuilt of Operator images to fix EC issues for prod
  .konflux/patches/.placeholder
  .konflux/patches/test.txt
Labels: approved

#2739 Update dockerfile to combine copy commands
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
Labels: approved

#2748 Update project.yaml
  project.yaml
Labels: approved

#2767 Update Dockerfile.catalog to rebuild 4.16 index image
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
Labels: approved

#2801 [next] update csv, index and render template to point to the correct bundle name
  .github/workflows/index-render-template.yaml
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/catalog-template.json
  hack/index-render-template.sh
Labels: approved

#2808 [bot:release-v1.17.x] update konflux configuration
  .github/workflows/update-sources.yaml
  .konflux/next/application.yaml
  .konflux/next/component-bundle.yaml
  .konflux/next/component-operator.yaml
  .konflux/next/component-proxy.yaml
  .konflux/next/component-webhook.yaml
  .konflux/next/image-bundle.yaml
  .konflux/next/image-operator.yaml
  .konflux/next/image-proxy.yaml
  .konflux/next/image-webhook.yaml
  .konflux/next/tests.yaml
  .tekton/operator-1-17-bundle-pull-request.yaml
  .tekton/operator-1-17-bundle-push.yaml
  .tekton/operator-1-17-operator-pull-request.yaml
  .tekton/operator-1-17-operator-push.yaml
  .tekton/operator-1-17-proxy-pull-request.yaml
  .tekton/operator-1-17-proxy-push.yaml
  .tekton/operator-1-17-webhook-pull-request.yaml
  .tekton/operator-1-17-webhook-push.yaml
Labels: automated, hack

#2809 [bot:main] update konflux configuration
  .github/workflows/update-sources-release-v1.17.x.yaml
  .konflux/main/application.yaml
  .konflux/main/component-bundle.yaml
  .konflux/main/component-operator.yaml
  .konflux/main/component-proxy.yaml
  .konflux/main/component-webhook.yaml
  .konflux/main/image-bundle.yaml
  .konflux/main/image-operator.yaml
  .konflux/main/image-proxy.yaml
  .konflux/main/image-webhook.yaml
  .konflux/main/tests.yaml
  .tekton/boussole.yaml
Labels: approved, lgtm, automated, hack

#2815 Update version for project, csv and index
  .konflux/olm-catalog/bundle/Dockerfile
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
  hack/index-render-template.sh
  project.yaml
Labels: approved

#2816 Update csv
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved

#2837 Update operator-next-index-4-17-push.yaml
  .tekton/operator-next-index-4-17-push.yaml
Labels: approved

#2838 Add fbc-build to main similar to docker-build-ta pipeline
  .tekton/fbc-build.yaml
Labels: approved

#2823 [bot:release-v1.17.x] update konflux configuration
  .tekton/operator-1-17-bundle-pull-request.yaml
  .tekton/operator-1-17-bundle-push.yaml
  .tekton/operator-1-17-operator-pull-request.yaml
  .tekton/operator-1-17-operator-push.yaml
  .tekton/operator-1-17-proxy-pull-request.yaml
  .tekton/operator-1-17-proxy-push.yaml
  .tekton/operator-1-17-webhook-pull-request.yaml
  .tekton/operator-1-17-webhook-push.yaml
Labels: automated, hack

#2840 [bot:main] update konflux configuration
  .github/workflows/update-sources-release-v1.17.x.yaml
Labels: automated, hack

#2849 [bot:release-v1.17.x] update konflux configuration
  .tekton/operator-1-17-bundle-pull-request.yaml
  .tekton/operator-1-17-bundle-push.yaml
  .tekton/operator-1-17-operator-pull-request.yaml
  .tekton/operator-1-17-operator-push.yaml
  .tekton/operator-1-17-proxy-pull-request.yaml
  .tekton/operator-1-17-proxy-push.yaml
  .tekton/operator-1-17-webhook-pull-request.yaml
  .tekton/operator-1-17-webhook-push.yaml
Labels: automated, hack

#2851 [bot:release-v1.17.x] update konflux configuration
  .tekton/operator-1-17-bundle-push.yaml
  .tekton/operator-1-17-operator-push.yaml
  .tekton/operator-1-17-proxy-push.yaml
  .tekton/operator-1-17-webhook-push.yaml
Labels: automated, hack

#2880 [1-17]Update dockerfile,tekton,hack and olm-catalog for 1.17
  .github/workflows/index-render-template.yaml
  .github/workflows/operator-update-images.yaml
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
  .konflux/olm-catalog/bundle/Dockerfile
  .konflux/olm-catalog/bundle/metadata/annotations.yaml
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/catalog-template.json
  .konflux/prefetch/artifacts.lock.yaml
  .tekton/operator-next-index-4-15-pull-request.yaml
  .tekton/operator-next-index-4-15-push.yaml
  .tekton/operator-next-index-4-16-pull-request.yaml
  .tekton/operator-next-index-4-16-push.yaml
  .tekton/operator-next-index-4-17-pull-request.yaml
  .tekton/operator-next-index-4-17-push.yaml
  .tekton/operator-next-index-4-18-pull-request.yaml
  .tekton/operator-next-index-4-18-push.yaml
  hack/index-render-template.sh
  hack/operator-update-images.sh
  project.yaml
Labels: approved

#2887 Update Makefile to remove update_versions for release branch
  Makefile
Labels: approved

#2881 [next]Update dockerfile
  .github/workflows/index-render-template.yaml
  .github/workflows/operator-update-images.yaml
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
  .konflux/prefetch/artifacts.lock.yaml
Labels: approved

#2889 [1-17]Update dockerfile
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
Labels: approved

#2930 Update Makefile
  Makefile
Labels: approved

#2946 [bot:main] update konflux configuration
  .github/workflows/auto-merge-release-v1.17.x.yaml
  .github/workflows/update-sources-release-v1.17.x.yaml
Labels: automated, hack

#2983 Fix missing separator issue Makefile
  Makefile
Labels: approved

#2984 Remove manual-approval-gate changes from fetch-payload.sh file
  hack/operator-fetch-payload.sh
Labels: approved

#2990 [bot:main] update konflux configuration
  .github/workflows/auto-merge-main.yaml
  .github/workflows/update-sources-main.yaml
  .tekton/operator-main-bundle-pull-request.yaml
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-pull-request.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-pull-request.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-pull-request.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: automated, hack

#2995 Update dockerfile
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
Labels: approved

#3003 Update Dockerfile to add extra labels
  .konflux/olm-catalog/bundle/Dockerfile
Labels: approved

#3006 Add konflux configuration for index images
  .konflux/index-configurations/application-index-4.12.yaml
  .konflux/index-configurations/application-index-4.13.yaml
  .konflux/index-configurations/application-index-4.14.yaml
  .konflux/index-configurations/application-index-4.15.yaml
  .konflux/index-configurations/application-index-4.16.yaml
  .konflux/index-configurations/application-index-4.17.yaml
  .konflux/index-configurations/application-index-4.18.yaml
  .konflux/index-configurations/component-index-4.12.yaml
  .konflux/index-configurations/component-index-4.13.yaml
  .konflux/index-configurations/component-index-4.14.yaml
  .konflux/index-configurations/component-index-4.15.yaml
  .konflux/index-configurations/component-index-4.16.yaml
  .konflux/index-configurations/component-index-4.17.yaml
  .konflux/index-configurations/component-index-4.18.yaml
  .konflux/index-configurations/image-index-4.12.yaml
  .konflux/index-configurations/image-index-4.13.yaml
  .konflux/index-configurations/image-index-4.14.yaml
  .konflux/index-configurations/image-index-4.15.yaml
  .konflux/index-configurations/image-index-4.16.yaml
  .konflux/index-configurations/image-index-4.17.yaml
  .konflux/index-configurations/image-index-4.18.yaml
  .konflux/index-configurations/tests-index-4-12.yaml
  .konflux/index-configurations/tests-index-4-13.yaml
  .konflux/index-configurations/tests-index-4-14.yaml
  .konflux/index-configurations/tests-index-4-15.yaml
  .konflux/index-configurations/tests-index-4-16.yaml
  .konflux/index-configurations/tests-index-4-17.yaml
  .konflux/index-configurations/tests-index-4-18.yaml
Labels: approved

#3005 Add tekton file for 4.12 to 4.18 index images
  .tekton/operator-1-14-index-4-12-pull-request.yaml
  .tekton/operator-1-14-index-4-12-push.yaml
  .tekton/operator-1-14-index-4-13-pull-request.yaml
  .tekton/operator-1-14-index-4-13-push.yaml
  .tekton/operator-1-14-index-4-14-pull-request.yaml
  .tekton/operator-1-14-index-4-14-push.yaml
  .tekton/operator-1-14-index-4-15-pull-request.yaml
  .tekton/operator-1-14-index-4-15-push.yaml
  .tekton/operator-1-14-index-4-16-pull-request.yaml
  .tekton/operator-1-14-index-4-16-push.yaml
  .tekton/operator-1-14-index-4-17-pull-request.yaml
  .tekton/operator-1-14-index-4-17-push.yaml
  .tekton/operator-1-14-index-4-18-pull-request.yaml
  .tekton/operator-1-14-index-4-18-push.yaml
Labels: approved

#3014 Update project.yaml
  project.yaml
Labels: approved

#3015 Update index-render-template.sh
  hack/index-render-template.sh
Labels: approved

#3033 Update BUNDLE_NAME to 1.14.6
  hack/index-render-template.sh
Labels: approved

#3035 Update operator-fetch-payload.sh
  hack/operator-fetch-payload.sh
Labels: approved

#3037 Check fetch payload file behaviour
  .github/workflows/update-sources-release-v1.14.x-test.yaml
Labels: approved

#3038 Update workflow name
  .github/workflows/update-sources-release-v1.14.x-test.yaml
Labels: approved

#3042 Update fetch payload file
  hack/operator-fetch-payload.sh
Labels: approved

#3043 Update test GH file
  .github/workflows/update-sources-release-v1.14.x-test.yaml
Labels: approved

#3044 Update update-sources-release-v1.14.x-test.yaml
  .github/workflows/update-sources-release-v1.14.x-test.yaml
Labels: approved

#3051 Update project.yaml
  project.yaml
Labels: approved

#3059 Change base image for ose-operator-registry
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3076 Add devel releaseplan for all index images
  .konflux/index-configurations/release-plan-4-12.yaml
  .konflux/index-configurations/release-plan-4-13.yaml
  .konflux/index-configurations/release-plan-4-14.yaml
  .konflux/index-configurations/release-plan-4-15.yaml
  .konflux/index-configurations/release-plan-4-16.yaml
  .konflux/index-configurations/release-plan-4-17.yaml
  .konflux/index-configurations/release-plan-4-18.yaml
Labels: approved

#3078 Update project.yaml witn tkn SHA
  project.yaml
Labels: approved

#3091 Retrigger 4.17 and 4.13 FBC
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
Labels: approved

#3092 Retrigger 4.14 FBC
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
Labels: approved

#3115 Update go to 1.22
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
Labels: approved

#3122 Update project.yaml
  project.yaml
Labels: approved

#3123 [bot:main] update konflux configuration
  .github/workflows/update-sources-main.yaml
Labels: automated, hack

#3125 Update project.yaml
  project.yaml
Labels: approved

#3129 Update project.yaml
  project.yaml
Labels: approved

#3144 [bot:main] update konflux configuration
  .github/workflows/update-sources-main.yaml
Labels: automated, hack

#3155 Update project.yaml
  project.yaml
Labels: approved

#3157 Update project.yaml
  project.yaml
Labels: approved

#3168 Update Dockerfile.catalog
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
Labels: approved

#3191 Update project.yaml
  project.yaml
Labels: approved
