Repository openshift-pipelines/operator, pull requests merged in 2025-02, with the labels that each got.

#1505 update dockerfile for bundle image
  .konflux/olm-catalog/bundle/Dockerfile
Labels: approved

#1507 remove unused directory next
  .konflux/tekton/next/.tekton/docker-build-ta.yaml
Labels: approved

#1545 [release-v1.18.x]update project.yaml
  project.yaml
Labels: approved

#1547 Delete .github/workflows/update-sources.1.18.yaml
  .github/workflows/update-sources.1.18.yaml
Labels: approved

#1548 Revert "Delete .github/workflows/update-sources.1.18.yaml"
  .github/workflows/update-sources.1.18.yaml
Labels: approved

#1549 Update update-sources.1.18.yaml
  .github/workflows/update-sources.1.18.yaml
Labels: approved

#1550 Update update-sources.1.18.yaml
  .github/workflows/update-sources.1.18.yaml
Labels: approved

#1573 [1.18.x]Add render template workflow for 1.18
  .github/workflows/index-render-template-1-18.yaml
Labels: approved

#1576 [1.18.x]Update sha in catalog-template.json
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
Labels: approved

#1574 [1.18.x]Update channel for 1.18
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
Labels: approved

#1599 Update operator-1-18-bundle-push.yaml to include build.appstudio.openshift.io/build-nudge-files annotation
  .tekton/operator-1-18-bundle-push.yaml
Labels: approved

#1602 Update CEL expression for index tekton yaml
  .tekton/operator-1-18-index-4-15-pull-request.yaml
  .tekton/operator-1-18-index-4-15-push.yaml
  .tekton/operator-1-18-index-4-16-pull-request.yaml
  .tekton/operator-1-18-index-4-16-push.yaml
  .tekton/operator-1-18-index-4-17-pull-request.yaml
  .tekton/operator-1-18-index-4-17-push.yaml
Labels: approved

#1600 Update operator-next-bundle-push.yaml to include build.appstudio.openshift.io/build-nudge-files annotation
  .tekton/operator-next-bundle-push.yaml
Labels: approved

#1603 Update CEL expression for index tekton yaml
  .tekton/operator-next-index-4-15-pull-request.yaml
  .tekton/operator-next-index-4-15-push.yaml
  .tekton/operator-next-index-4-16-pull-request.yaml
  .tekton/operator-next-index-4-16-push.yaml
  .tekton/operator-next-index-4-17-pull-request.yaml
  .tekton/operator-next-index-4-17-push.yaml
Labels: approved, lgtm

#1340 Add e2e for manualapprovalgate and chains
  .konflux/tekton/bundle-e2e-pipeline.yaml
  docs/E2E.md
Labels: approved, lgtm

#1643 Add separate application for index images
  .konflux/1.18/application-index-4.15.yaml
  .konflux/1.18/application-index-4.16.yaml
  .konflux/1.18/application-index-4.17.yaml
  .konflux/1.18/component-index-4.15.yaml
  .konflux/1.18/component-index-4.16.yaml
  .konflux/1.18/component-index-4.17.yaml
  .konflux/1.18/image-index-4.15.yaml
  .konflux/1.18/image-index-4.16.yaml
  .konflux/1.18/image-index-4.17.yaml
  .konflux/1.18/tests-index-4-15.yaml
  .konflux/1.18/tests-index-4-16.yaml
  .konflux/1.18/tests-index-4-17.yaml
Labels: approved

#1644 Update yaml files with new index application name
  .konflux/olm-catalog/bundle/Dockerfile
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .tekton/operator-1-18-index-4-15-pull-request.yaml
  .tekton/operator-1-18-index-4-15-push.yaml
  .tekton/operator-1-18-index-4-16-pull-request.yaml
  .tekton/operator-1-18-index-4-16-push.yaml
  .tekton/operator-1-18-index-4-17-pull-request.yaml
  .tekton/operator-1-18-index-4-17-push.yaml
Labels: approved

#1645 Update versions in catalog template and dockerfile
  .konflux/olm-catalog/bundle/Dockerfile
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/catalog-template.json
Labels: approved

#1658 Add multiarch for fbc pipeline
  .tekton/fbc-build.yaml
  .tekton/operator-1-18-index-4-15-pull-request.yaml
  .tekton/operator-1-18-index-4-16-pull-request.yaml
  .tekton/operator-1-18-index-4-17-pull-request.yaml
Labels: approved

#1660 [bot:next] update konflux configuration
  .tekton/operator-next-bundle-pull-request.yaml
  .tekton/operator-next-bundle-push.yaml
Labels: automated, hack

#1703 Add/Update the keys for images
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  project.yaml
Labels: approved

#1750 Revert "Add multiarch for fbc pipeline"
  .tekton/fbc-build.yaml
  .tekton/operator-1-18-index-4-15-pull-request.yaml
  .tekton/operator-1-18-index-4-16-pull-request.yaml
  .tekton/operator-1-18-index-4-17-pull-request.yaml
Labels: approved

#1755 update operator-update-images.sh to avoid replacing the images
  hack/operator-update-images.sh
Labels: approved

#1757 Delete .konflux/1.18/tests-e2e-tektoncd-pipelines.yaml
  .konflux/1.18/tests-e2e-tektoncd-pipelines.yaml
Labels: approved

#1765 Add missed pac cli image to csv
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  .konflux/olm-catalog/index/v4.16/catalog/openshift-pipelines-operator-rh/catalog.json
Labels: approved

#1766 Add missed pac cli image to csv
  .konflux/olm-catalog/index/v4.15/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.17/catalog/openshift-pipelines-operator-rh/catalog.json
Labels: approved

#1817 add reference for IMAGE_PAC_PAC_CLI for next
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  .konflux/olm-catalog/index/v4.15/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.16/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.17/catalog/openshift-pipelines-operator-rh/catalog.json
  project.yaml
Labels: approved

#1823 Remove project.yaml from CEL Expression
  .tekton/operator-next-bundle-pull-request.yaml
  .tekton/operator-next-bundle-push.yaml
Labels: approved, lgtm

#1828 update e2e to run with index images
  .konflux/tekton/bundle-e2e-pipeline.yaml
Labels: approved, lgtm

#1850 Delete .tekton/docker-build-ta.yaml
  .tekton/docker-build-ta.yaml
Labels: approved, lgtm

#1864 Update title of bot PR generated for update CSV
  .github/workflows/operator-update-images-next.yaml
Labels: approved, lgtm

#1865 Add missing annotation
  .tekton/operator-next-bundle-push.yaml
Labels: approved, lgtm

#1871 Add application, component, image and test for 4.18 index
  .konflux/1.18/application-index-4.18.yaml
  .konflux/1.18/component-index-4.18.yaml
  .konflux/1.18/image-index-4.18.yaml
  .konflux/1.18/tests-index-4-18.yaml
Labels: approved

#1891 Add entry for sidecarlogresults image in project and csv yaml
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  .konflux/olm-catalog/index/v4.15/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.16/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.17/catalog/openshift-pipelines-operator-rh/catalog.json
  .konflux/olm-catalog/index/v4.18/catalog/openshift-pipelines-operator-rh/catalog.json
  project.yaml
Labels: approved

#1899 Update csv workflow to add lgtm and approved labels
  .github/workflows/operator-update-images-next.yaml
Labels: approved, lgtm

#1905 Next
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm

#1914 Update csv workflow to add lgtm and approved labels
  .github/workflows/operator-update-images-next.yaml
Labels: approved, lgtm

#1956 Add Tekton Caches Images in project.yaml
  project.yaml
Labels: approved, lgtm

#1952 Add FIPS compliance config
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
  .tekton/operator-1-18-bundle-pull-request.yaml
  .tekton/operator-1-18-bundle-push.yaml
Labels: approved

#1957 update channel and version for CSV
  .konflux/olm-catalog/bundle/Dockerfile
  .konflux/olm-catalog/bundle/metadata/annotations.yaml
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/catalog-template.json
  Makefile
  hack/update-version.sh
  project.yaml
Labels: approved, lgtm

#1984 Update update-sources.1.18.yaml
  .github/workflows/update-sources.1.18.yaml
Labels: approved

#2000 Update rpms.lock.yaml to match with latest ec policy
  .konflux/rpms/rpms.in.yaml
  .konflux/rpms/rpms.lock.yaml
  .konflux/rpms/ubi.repo
Labels: approved, lgtm

#2007 Fix operator-update-images-next.yaml
  .github/workflows/operator-update-images-next.yaml
Labels: approved, lgtm

#2009 Update e2e IntegrationTestScenario to run with index images
  .konflux/main/tests-e2e-tektoncd-pipelines.yaml
Labels: approved, lgtm

#2016 Update Tekton CEL for Index Images.
  .tekton/operator-next-index-4-15-pull-request.yaml
  .tekton/operator-next-index-4-15-push.yaml
  .tekton/operator-next-index-4-16-pull-request.yaml
  .tekton/operator-next-index-4-16-push.yaml
  .tekton/operator-next-index-4-17-pull-request.yaml
  .tekton/operator-next-index-4-17-push.yaml
Labels: approved, lgtm

#2076 Fix RPMs
  .konflux/rpms/rpms.in.yaml
  .konflux/rpms/rpms.lock.yaml
Labels: approved, lgtm

#2092 Update docker-build-ta.yaml
  .tekton/docker-build-ta.yaml
Labels: approved

#2104 Update size for s390x
  .tekton/docker-build-ta.yaml
Labels: approved

#2031 [bot:next] update konflux configuration
  .github/workflows/update-sources.next.yaml
  .konflux/next/application.yaml
  .konflux/next/component-bundle.yaml
  .konflux/next/component-operator.yaml
  .konflux/next/component-proxy.yaml
  .konflux/next/component-webhook.yaml
  .konflux/next/image-bundle.yaml
  .konflux/next/image-operator.yaml
  .konflux/next/image-proxy.yaml
  .konflux/next/image-webhook.yaml
  .konflux/next/tests.yaml
  .tekton/operator-next-bundle-pull-request.yaml
  .tekton/operator-next-bundle-push.yaml
  .tekton/operator-next-operator-push.yaml
  .tekton/operator-next-proxy-push.yaml
  .tekton/operator-next-webhook-push.yaml
Labels: automated, hack

#2033 [bot:main] update konflux configuration
  .github/workflows/update-sources.1.18.yaml
  .github/workflows/update-sources.next.yaml
  .konflux/1.18/application.yaml
  .konflux/1.18/component-operator.yaml
  .konflux/1.18/component-proxy.yaml
  .konflux/1.18/component-webhook.yaml
  .konflux/1.18/image-operator.yaml
  .konflux/1.18/image-proxy.yaml
  .konflux/1.18/image-webhook.yaml
  .konflux/1.18/tests.yaml
  .konflux/main/component-bundle.yaml
  .konflux/main/image-bundle.yaml
  .konflux/next/application.yaml
  .konflux/next/component-operator.yaml
  .konflux/next/component-proxy.yaml
  .konflux/next/component-webhook.yaml
  .konflux/next/image-operator.yaml
  .konflux/next/image-proxy.yaml
  .konflux/next/image-webhook.yaml
  .konflux/next/release-plan.yaml
  .konflux/next/tests.yaml
  .tekton/operator-main-bundle-pull-request.yaml
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-push.yaml
  .tekton/prow.yaml
Labels: automated, hack

#2107 Update docker-build-ta.yaml
  .tekton/docker-build-ta.yaml
Labels: approved

#2108 Update docker-build-ta.yaml
  .tekton/docker-build-ta.yaml
Labels: approved

#2109 Update docker-build-ta.yaml
  .tekton/docker-build-ta.yaml
Labels: approved

#2110 Add multiarch for fbc pipeline
  .tekton/fbc-build.yaml
  .tekton/operator-1-18-index-4-15-pull-request.yaml
  .tekton/operator-1-18-index-4-16-pull-request.yaml
  .tekton/operator-1-18-index-4-17-pull-request.yaml
  .tekton/operator-1-18-index-4-18-pull-request.yaml
Labels: approved

#2142 Create test-1-18.yaml
  .github/workflows/test-1-18.yaml
Labels: approved

#2143 Update test-1-18.yaml
  .github/workflows/test-1-18.yaml
Labels: approved

#2145 Fix EC by changing the rpms
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
  .konflux/rpms/rpms.in.yaml
  .konflux/rpms/rpms.lock.yaml
  .konflux/rpms/ubi.repo
Labels: approved

#2165 Removed ecosystem-cert-preflight-checks from build pipleine to fix EC issue on bundle image
  .tekton/docker-build-ta.yaml
Labels: approved, lgtm

#2177 Update test-1-18.yaml
  .github/workflows/test-1-18.yaml
Labels: approved

#2172 [bot:release-v1.18.x] update konflux configuration
  .konflux/1.18/image-bundle.yaml
  .konflux/1.18/image-operator.yaml
  .konflux/1.18/image-proxy.yaml
  .konflux/1.18/image-webhook.yaml
  .tekton/operator-1-18-bundle-pull-request.yaml
  .tekton/operator-1-18-bundle-push.yaml
  .tekton/operator-1-18-operator-pull-request.yaml
  .tekton/operator-1-18-operator-push.yaml
  .tekton/operator-1-18-proxy-pull-request.yaml
  .tekton/operator-1-18-proxy-push.yaml
  .tekton/operator-1-18-webhook-pull-request.yaml
  .tekton/operator-1-18-webhook-push.yaml
Labels: automated, hack

#2258 Testing render template
  .github/workflows/index-render-template-1-18-test.yaml
Labels: approved

#2259 Testing render template index images
  .konflux/olm-catalog/index/v4.15/catalog-template.json
Labels: approved

#2260 Update Dockerfile to test bundle image
  .konflux/olm-catalog/bundle/Dockerfile
Labels: approved

#2263 Update catalog-template.json
  .konflux/olm-catalog/index/v4.15/catalog-template.json
Labels: approved

#2302 Update project.yaml
  project.yaml
Labels: approved

#2320 Update project.yaml
  project.yaml
Labels: approved

#2332 Update dockerfile
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#2363 Update fbc-build.yaml
  .tekton/fbc-build.yaml
Labels: approved

#2395 Update project.yaml
  project.yaml
Labels: approved

#2404 [bot:main] update konflux configuration
  .konflux/main/component-bundle.yaml
Labels: automated, hack

#2405 [bot:release-v1.18.x] update konflux configuration
  .konflux/1.18/component-bundle.yaml
Labels: automated, hack

#2412 update tekton files to remove fbc-build.yaml pathchange
  .tekton/operator-next-index-4-15-pull-request.yaml
  .tekton/operator-next-index-4-15-push.yaml
  .tekton/operator-next-index-4-16-pull-request.yaml
  .tekton/operator-next-index-4-16-push.yaml
  .tekton/operator-next-index-4-17-pull-request.yaml
  .tekton/operator-next-index-4-17-push.yaml
  .tekton/operator-next-index-4-18-pull-request.yaml
  .tekton/operator-next-index-4-18-push.yaml
Labels: approved

#2456 Update project yaml to revert the updated SHA as those are not code changes
  project.yaml
Labels: approved

#2457 Update operator-update-images.yaml
  .github/workflows/operator-update-images.yaml
Labels: approved

#2460 Update project yaml and csv with new SHA
  .konflux/olm-catalog/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  project.yaml
Labels: approved
