Repository openshift-pipelines/operator, pull requests merged in 2025-04, with the labels that each got.

#3195 Update project.yaml
  project.yaml
Labels: approved

#3210 [bot:main] update konflux configuration
  .tekton/operator-main-bundle-pull-request.yaml
  .tekton/operator-main-operator-pull-request.yaml
  .tekton/operator-main-proxy-pull-request.yaml
  .tekton/operator-main-webhook-pull-request.yaml
Labels: approved, lgtm, automated, hack

#3213 [bot:main] update konflux configuration
  .tekton/operator-main-bundle-pull-request.yaml
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-pull-request.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-pull-request.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-pull-request.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: approved, lgtm, automated, hack

#3218 Update Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
Labels: approved

#3221 [bot:main] update konflux configuration
  .github/workflows/update-sources-main.yaml
Labels: automated, hack

#3235 Update proxy.Dockerfile to rebuild proxy
  .konflux/dockerfiles/proxy.Dockerfile
Labels: approved

#3248 Update docker-build-ta.yaml
  .tekton/docker-build-ta.yaml
Labels: approved, lgtm

#3247 [bot:main] update konflux configuration
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: automated, hack

#3280 Rebuild index images
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3360 Update project.yaml
  project.yaml
Labels: approved

#3386 Update SHA
  project.yaml
Labels: approved

#3390 Update project.yaml
  project.yaml
Labels: approved

#3398 Update dockerfile to build index image
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
Labels: approved

#3400 Update Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3428 [bot:main] update konflux configuration
  .github/workflows/update-sources-main.yaml
  .tekton/operator-main-bundle-pull-request.yaml
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-pull-request.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-pull-request.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-pull-request.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: automated, hack

#3452 [bot:main] update konflux configuration
  .tekton/operator-main-bundle-push.yaml
  .tekton/operator-main-operator-push.yaml
  .tekton/operator-main-proxy-push.yaml
  .tekton/operator-main-webhook-push.yaml
Labels: automated, hack

#3474 Update dockerfile to build 4.14 to 4.18 index images
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3475 Update index graph to add older channel
  .konflux/olm-catalog/index/v4.12/catalog-template.json
  .konflux/olm-catalog/index/v4.13/catalog-template.json
  .konflux/olm-catalog/index/v4.14/catalog-template.json
Labels: approved

#3458 [bot:main] update konflux configuration
  .github/workflows/update-sources-next.yaml
Labels: automated, hack

#3495 [bot:next] update konflux configuration
  .tekton/operator-next-bundle-pull-request.yaml
  .tekton/operator-next-bundle-push.yaml
  .tekton/operator-next-operator-pull-request.yaml
  .tekton/operator-next-operator-push.yaml
  .tekton/operator-next-proxy-pull-request.yaml
  .tekton/operator-next-proxy-push.yaml
  .tekton/operator-next-webhook-pull-request.yaml
  .tekton/operator-next-webhook-push.yaml
Labels: approved, lgtm, automated, hack

#3507 Update Dockerfile
  .konflux/olm-catalog/bundle/Dockerfile
Labels: approved

#3501 [bot:next] update konflux configuration
  .tekton/operator-next-index-4-15-pull-request.yaml
  .tekton/operator-next-index-4-15-push.yaml
  .tekton/operator-next-index-4-16-pull-request.yaml
  .tekton/operator-next-index-4-16-push.yaml
  .tekton/operator-next-index-4-17-pull-request.yaml
  .tekton/operator-next-index-4-17-push.yaml
  .tekton/operator-next-index-4-18-pull-request.yaml
  .tekton/operator-next-index-4-18-push.yaml
Labels: automated, hack

#3508 [bot:next] update konflux configuration
  .tekton/operator-next-index-4-15-pull-request.yaml
  .tekton/operator-next-index-4-15-push.yaml
  .tekton/operator-next-index-4-16-pull-request.yaml
  .tekton/operator-next-index-4-16-push.yaml
  .tekton/operator-next-index-4-17-pull-request.yaml
  .tekton/operator-next-index-4-17-push.yaml
  .tekton/operator-next-index-4-18-pull-request.yaml
  .tekton/operator-next-index-4-18-push.yaml
Labels: automated, hack

#3513 [bot:next] update konflux configuration
  .tekton/operator-next-bundle-pull-request.yaml
  .tekton/operator-next-bundle-push.yaml
  .tekton/operator-next-operator-pull-request.yaml
  .tekton/operator-next-operator-push.yaml
  .tekton/operator-next-proxy-pull-request.yaml
  .tekton/operator-next-proxy-push.yaml
  .tekton/operator-next-webhook-pull-request.yaml
  .tekton/operator-next-webhook-push.yaml
Labels: approved, lgtm, automated, hack

#3534 [bot:next] update konflux configuration
  .tekton/operator-next-index-4-15-push.yaml
  .tekton/operator-next-index-4-16-push.yaml
  .tekton/operator-next-index-4-17-push.yaml
  .tekton/operator-next-index-4-18-push.yaml
Labels: automated, hack

#3565 [bot:main] update konflux configuration
  .github/workflows/auto-merge-upstream-next.yaml
Labels: automated, hack

#3567 Update project.yaml
  project.yaml
Labels: approved

#3582 Fix missing separator issue in Makefile
  Makefile
Labels: approved

#3596 [bot:openshift-pipelines-index-4.12:next] update konflux configuration
  .tekton/operator-next-index-4.12-pull-request.yaml
  .tekton/operator-next-index-4.12-push.yaml
Labels: automated, hack

#3701 Update Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
Labels: approved

#3714 Rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3721 [bot:openshift-pipelines-index-4.17:next] update konflux configuration
  .tekton/operator-next-index-4.17-pull-request.yaml
  .tekton/operator-next-index-4.17-push.yaml
Labels: automated, hack

#3733 [bot:openshift-pipelines-index-4.18:next] update konflux configuration
  .tekton/operator-next-index-4.18-pull-request.yaml
  .tekton/operator-next-index-4.18-push.yaml
Labels: automated, hack

#3738 Update project.yaml
  project.yaml
Labels: approved

#3743 [bot:openshift-pipelines-operator:next] update konflux configuration
  .tekton/operator-next-bundle-push.yaml
Labels: automated, hack

#3752 Update project.yaml
  project.yaml
Labels: approved

#3760 Rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3774 [bot:openshift-pipelines-index-4.18:next] update konflux configuration
  .tekton/operator-next-index-4.18-pull-request.yaml
  .tekton/operator-next-index-4.18-push.yaml
Labels: automated, hack

#3781 Change go verion to 1.23 to fix GLIBC error
  .konflux/dockerfiles/operator.Dockerfile
  .konflux/dockerfiles/proxy.Dockerfile
  .konflux/dockerfiles/webhook.Dockerfile
Labels: approved

#3801 Update fbc-build.yaml
  .tekton/fbc-build.yaml
Labels: approved

#3803 Update default channel in 4.12
  .konflux/olm-catalog/index/v4.12/catalog-template.json
Labels: approved

#3799 Create .placeholder
  .konflux/patches/.placeholder
Labels: approved, lgtm

#3826 Update project.yaml
  project.yaml
Labels: approved

#3844 rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3937 rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#3963 Update project.yaml
  project.yaml
Labels: approved

#3971 Rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4016 Rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved

#4020 Update project, dockerfile and index-render-template files
  .konflux/olm-catalog/bundle/Dockerfile
  hack/index-render-template.sh
  project.yaml
Labels: approved

#4042 Update operator-update-images.yaml
  .github/workflows/operator-update-images.yaml
Labels: approved

#4049 Update index configurations
  .konflux/index-configurations/application-index-4.15.yaml
  .konflux/index-configurations/application-index-4.16.yaml
  .konflux/index-configurations/application-index-4.17.yaml
  .konflux/index-configurations/application-index-4.18.yaml
  .konflux/index-configurations/component-index-4.15.yaml
  .konflux/index-configurations/component-index-4.16.yaml
  .konflux/index-configurations/component-index-4.17.yaml
  .konflux/index-configurations/component-index-4.18.yaml
  .konflux/index-configurations/image-index-4.15.yaml
  .konflux/index-configurations/image-index-4.16.yaml
  .konflux/index-configurations/image-index-4.17.yaml
  .konflux/index-configurations/image-index-4.18.yaml
  .konflux/index-configurations/release-plan-4-15.yaml
  .konflux/index-configurations/release-plan-4-16.yaml
  .konflux/index-configurations/release-plan-4-17.yaml
  .konflux/index-configurations/release-plan-4-18.yaml
  .konflux/index-configurations/tests-index-4-15.yaml
  .konflux/index-configurations/tests-index-4-16.yaml
  .konflux/index-configurations/tests-index-4-17.yaml
  .konflux/index-configurations/tests-index-4-18.yaml
  .konflux/olm-catalog/index/v4.15/catalog-template.json
  .konflux/olm-catalog/index/v4.16/catalog-template.json
  .konflux/olm-catalog/index/v4.17/catalog-template.json
  .konflux/olm-catalog/index/v4.18/catalog-template.json
  .tekton/operator-1-18-index-4-15-pull-request.yaml
  .tekton/operator-1-18-index-4-15-push.yaml
  .tekton/operator-1-18-index-4-16-pull-request.yaml
  .tekton/operator-1-18-index-4-16-push.yaml
  .tekton/operator-1-18-index-4-17-pull-request.yaml
  .tekton/operator-1-18-index-4-17-push.yaml
  .tekton/operator-1-18-index-4-18-pull-request.yaml
  .tekton/operator-1-18-index-4-18-push.yaml
Labels: approved

#4050 Update index-render-template.yaml
  .github/workflows/index-render-template.yaml
Labels: approved

#4122 [1-18-1] Rebuild index images
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
  .tekton/fbc-build.yaml
Labels: approved

#4124 Update project.yaml
  project.yaml
Labels: approved

#4126 Update project.yaml
  project.yaml
Labels: approved

#4136 [1-15-3] remove 4.13 index image
  .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.13/catalog-template.json
  .konflux/olm-catalog/index/v4.13/catalog/openshift-pipelines-operator-rh/catalog.json
Labels: approved

#4138 [1-15-3] remove 4.13 files
  .konflux/index-configurations/application-index-4.13.yaml
  .konflux/index-configurations/component-index-4.13.yaml
  .konflux/index-configurations/image-index-4.13.yaml
  .konflux/index-configurations/release-plan-4-13.yaml
  .konflux/index-configurations/tests-index-4-13.yaml
  .tekton/operator-1-15-index-4-13-pull-request.yaml
  .tekton/operator-1-15-index-4-13-push.yaml
Labels: approved

#4145 [1-15-3] rebuild index images
  .konflux/olm-catalog/index/v4.12/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
  .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
Labels: approved
